name: thosewhoplay
favicon: null
layout_spectrum: 0.65698
typography_spectrum: 0.8606834926176816
title: Those Who Play
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f0f2'
    - '#574a53'
    - '#cac8cc'
    - '#b2afb4'
    - '#7f7278'
  brandStrength: 0.9375
  lightness: 0.5492624095641077
  saturation: 0.625
  rhythmicContrast: 0.14592215116135776
purpose: []
