name: thosewhoplay
favicon: null
layout_spectrum: 0.65698
typography_spectrum: 0.8606834926176816
title: Those Who Play
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ef2e27'
    - '#d8d6c9'
    - '#000000'
    - '#8b1b16'
    - '#7f7e76'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
